### ISSUE TITLE
META: Standardize on a Timezone

### ISSUE THREAD

**Issue by mikemilano** [thinktandem/tandem#16]
1. Describe the problem and how you think it most impacts [Tandem's goals/mission/values](https://docs.thinktandem.io/manifesto/)

I'm proposing we standardize on a specific timezone for communication. Currently when throwing dates around, we need to either include a timezone or make an assumption based on who it's coming from.

If we were to standardize on Eastern time, it would be understood that times are EST unless another timezone was specified.

2. Briefly describe the "fastest" thing we could do to begin to make things right.

Adopt the proposal and establish the standard timezone.

3. Briefly describe a "better" and more automated/tied in solution and how that would be better than the fastest.

If we wanted to go all out, we could commission one of our engineers who is also a decent technical writer to document it.

4. Provide a few sentences about how you see this solution impacting various parts of the business

#### Operations

This would remove ambiguity which may prevent misunderstandings for meeting proposals and other time related details.

#### Marketing

N/A

#### Sales

N/A

#### Feels and Morale

Removing ambiguity removes cognitive overhead.

I see potential for someone feeling dumb, and others disappointed, if someone missed a meeting do to a misunderstanding... especially a client meeting.

5. Provide a _best estimate_ about a few things. Use the `better` solution to compute your estimate.

Rank things on a modified-fibonacci scale between 1-40 eg (1, 2, 3, 5, 8, 13, 21, 40).

```yaml
# How urgent is this?
Priority: 5


# How well does the proposed solution align with our values
Value Alignment: 21

# Story points we think this will take
# NOTE: do not set the actual story points on the ticket itself, we will use the
# points on subsequent action itmes
Effort: 1

# Value to various parts of the business
Operational Efficiency: 21
Marketing: N/A
Sales: N/A
Feels and Morale: 13
```

6. Add your entry to this spreadsheet with the above data.

@TODO: let's hold off on making this until we lock down the above a bit

7. How can we best distribute solution so it's in baked into our processes and not lost?

@TODO: maybe link to the "tie things" together part of this process

> Example: We could initially add a checklist entry for the "fastest" version of this into our "starting up a new project" documentation and make sure that doc is references in all our start states so people. Ideally a `lando init --source tandem` command would be how we start all new projects and that automatically stands up the tickets amongst other things.

8. Generate a rough list of action items based on the above, eventually these should become action items

> Example:
> - [ ] Decide on the timezone
> - [ ] Document it

9. Does anything above require discussion or feedback before this proposal is ready for primetime?

Ready to go

10. Make sure you complete the following checklist

- [x ] I've selected the label that _best_ describes what part of the business this ticket improves eg `sales`, `dev`, etc

@TODO: other things we should have here?
