### ISSUE TITLE
Create an Estimation Process

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/tandem#19]
**Problem**

In the past, Alec and John have thrown out a WAG (wild ass guess) after getting a broad overview of a project. There are several problems with this:

1. Leads to inaccurate estimates and inappropriate expectations.
2. Fails to engage developers, so the team who takes over the project isn't invested in the estimate and feels like they've been forced into a contract they didn't define.

Past efforts at creating a unified estimation process have been convoluted and haven't been uniformly adopted; as a result, we have multiple types of estimation sheets and no unified process that they belong to.

These issues cause Tandem to fail in reaching its goals of collaboration/transparency. It can also hurt our profits.

**How do we make it right?/Automated Solution**

Let's outline an estimation process that we all are invested in. This should include...

- Where does estimation fall in the sales process? (Outline Sales process and estimation's place)
- Steps for making an estimate.
- Estimation spreadsheet or other tool for outlining project scope.
- How much time should be spent outlining/estimating a project pre-contract.
- Highlighting importance of "discovery" in refining estimates post-contract (include discoveries in all our contract language).

**How does this impact the rest of the biz?**

#### Operations

Aassist in the sales -> engineering handoff, and hopefully improve our project results.

#### Marketing

We could potentially market our estimation process as a differentiator; other agencies have done variations on this.

#### Sales

This would help clarify roles in the sales process and make sales more efficient. The more standardized our sales process is, the more confident we can be in speaking to clients.

#### Feels and Morale

Less resentment of having estimates imposed upon developers and sales front-men not feeling like they have to wait around for a long-winded estimate process that invests too much up-front.

5. Provide a _best estimate_ about a few things. Use the `better` solution to compute your estimate.

```yaml
# How urgent is this?
Priority: 5

# How well does the proposed solution align with our values
Value Alignment: 10

# Story points we think this will take
# NOTE: do not set the actual story points on the ticket itself, we will use the
# points on subsequent action itmes
Effort: 21

# Value to various parts of the business
Operational Efficiency: 40
Marketing: 3
Sales: 40
Feels and Morale: 21
```

6. Add your entry to this spreadsheet with the above data.

@TODO: let's hold off on making this until we lock down the above a bit

7. How can we best distribute solution so it's in baked into our processes and not lost?

@TODO: maybe link to the "tie things" together part of this process

> Example: We could initially add a checklist entry for the "fastest" version of this into our "starting up a new project" documentation and make sure that doc is references in all our start states so people. Ideally a `lando init --source tandem` command would be how we start all new projects and that automatically stands up the tickets amongst other things.

8. Generate a rough list of action items based on the above, eventually these should become action items

- Where does estimation fall in the sales process? (Outline Sales process and estimation's place)
- Steps for making an estimate.
- Estimation spreadsheet or other tool for outlining project scope.
- How much time should be spent outlining/estimating a project pre-contract.
- Highlighting importance of "discovery" in refining estimates post-contract (include discoveries in all our contract language).

9. Does anything above require discussion or feedback before this proposal is ready for primetime?

Yes! Most of the above are discussion items with a few proposed action items. We need to all feel comfortable with our estimation process.
