### ISSUE TITLE
Can we simplify our Travis Config

### ISSUE THREAD

**Issue by dustinleblanc** [thinktandem/tandem#75]
No structure here, add whatever is helpful for you.

**Comment by pirog** [comment]
@dustinleblanc just dropping some notes here because i'd like to provide at least a high level sketch on some requirements here. also, while this is only a `note` i would like to say good job on an issue that is pretty digestible and discussable async on github! def need more things like that!

For things i total agree with

1. definitely should run the least amount of builds which im guessing would be 2 instead of 4. Note that there are differences on the travis end between a PR build and a branch build that may change things so while 1 may be possible there could be hidden monsters there so 2 is probably the "simplest" thing you can do that would work across all project types

Now for some requirements that i think are pretty important

1. 3 minutes is totally acceptable time so i dont thnk we gain a lot by making those faster especially if we have less total builds as you've suggested. this seems like an obvious trap and time suck to me
2. I think dogfooding lando is absolutely essential. this would allow us to maintain a very small amount of travis files (eg the ones in our start states) since we can use lando as an interface and set the implementation on a per project level eg we define what `lando test:unit` is.

I think the key to success here, and where our goals converge into the same vision is just having the "base" travis file for each start state have various things we can comment out as needed on a per project basis eg if we just want to lint/code and dont want to spin up a fully running site we dont have to. I think its easy to do this with the same travis file for all projects generated from a given start state eg

```yaml
before_install:
   - # Install lando via Hyperdrive
# Install dependencies
install: lando start
# Run tests
# Each one of these we can comment out as needed
script:
  - lando test:lint
  - lando test:cs
  - lando test:unit
  - lando pull --pull opts # get the site running, ideally seed a db but this is the easiest next step
  - lando test:functional # eg behat if this were a d8 project
```
